name: tezster_dart
description: A flutter package which provides the functionalities to play around
  with tezos dApps
version: 2.1.2-beta.2
homepage: https://github.com/Tezsure/tezster_dart
repository: https://github.com/Tezsure/tezster_dart
issue_tracker: https://github.com/Tezsure/tezster_dart/issues

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bip39: ^1.0.3
  blake2b: ^0.2.2
  bs58check: ^1.0.2
  convert: ^3.0.2
  crypto: ^3.0.2
  flutter_sodium: ^0.2.0
  unorm_dart: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
